_wandb:
    value:
        cli_version: 0.24.0
        e:
            uk1iiz895o3esxh201ih6e5dwass20cg:
                codePath: MLOps_project/.venv/bin/train
                codePathLocal: .venv/bin/train
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1081101176832"
                        used: "18331901952"
                email: zilverwood@gmail.com
                executable: /home/zilverwood/MLOps_Group_50/MLOps_project/.venv/bin/python3
                git:
                    commit: b6478ff38f44fbe0fd6e90e6e377943674b9904c
                    remote: https://github.com/DitteGilsfeldt/MLOps_Group_50
                host: BOOK-8PTVU9UD38
                memory:
                    total: "8099545088"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/zilverwood/MLOps_Group_50/MLOps_project/.venv/bin/train
                python: CPython 3.12.3
                root: /home/zilverwood/MLOps_Group_50/MLOps_project
                startedAt: "2026-01-15T14:42:47.430701Z"
                writerId: uk1iiz895o3esxh201ih6e5dwass20cg
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 49
                - 50
                - 63
            "2":
                - 1
                - 41
                - 49
                - 50
                - 63
            "3":
                - 16
            "4": 3.12.3
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 2
lr:
    value: 0.001
