name: Build and Push Docker to GCP
on:
  push:
    branches: [ "feat/docker-setup", "main", "henrik" ]  # Triggers on these branches

env:
  PROJECT_ID: lofty-root-484207-a0
  REGION: europe-west1
  REPOSITORY: group50-docker-repo
  IMAGE: emotion-app

jobs:
  build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MLOps_project  # This tells every step to start inside your project folder
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Uses the key your teammate added

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3  #

      - name: Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet  #

      - name: Build and Push
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest -f dockerfiles/api.dockerfile .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest